### ISSUE TITLE
RSAGA & rgdal   packages

### ISSUE THREAD

**Issue by txominbornaetxea** [maurorossi/LAND-SE#1]
Hi, 
I have run the software with a very good results, but before running it I had to install some packages apart from those mentioned in the user guide. 
Apart from the packages mentioned in the user manual (MASS, raster, etc…), during the test also “gdal” and “ RSAGA ” packages have been necessary to install. Fortunately, R advises you about it with an error message. 

I only wanted to pointed out this little detail. 
Ciao

**Comment by maurorossi** [comment]
Thanks for having highlighted this issue.
rgdal and RSAGA packages provide bindings to gdal and SAGA libraries. Those are not automatically installed when you add the rgdal and RSAGA packages.
In the next user guide version I'll add this additional info.
Mauro R.
